build:
	g++ -std=c++11 -o project2.out src/main.cpp src/Image.cpp

run: 
	./project2.out

clean:
	del output\part1.tga
	del output\part2.tga
	del output\part3.tga
	del output\part4.tga
	del output\part5.tga
	del output\part6.tga
	del output\part7.tga
	del output\part8_b.tga
	del output\part8_g.tga
	del output\part8_r.tga
	del output\part9.tga
	del output\part10.tga

